[
    {
        "domain": ".gemini.google.com",
        "expirationDate": 1812775858.202566,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GA1.1.2092490730.1770214179",
        "id": 1
    },
    {
        "domain": ".gemini.google.com",
        "expirationDate": 1812775858.201008,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga_BF8Q35BMLM",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GS2.1.s1778215144$o145$g1$t1778215858$j60$l0$h0",
        "id": 2
    },
    {
        "domain": ".gemini.google.com",
        "expirationDate": 1812775858.692759,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga_WC57KJ50ZZ",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GS2.1.s1778215142$o181$g1$t1778215858$j58$l0$h0",
        "id": 3
    },
    {
        "domain": ".gemini.google.com",
        "expirationDate": 1782639016,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_gcl_au",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1.1.792299493.1774863016",
        "id": 4
    },
    {
        "domain": ".gemini.google.com",
        "expirationDate": 1779021643.445877,
        "hostOnly": false,
        "httpOnly": true,
        "name": "COMPASS",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "gemini-pd=CjwACWuJV93jFYb_b6k1ZbZc5AVi75OXfwVJx6huPFdJgLZgT-iphNSBtyIyTho-2Gurv4U86El7hPmdVFUQ0LP3zwYaZgAJa4lXpMUDqFVhvXayopoShCupMZ4RLawHcFAuWARBhjOrJVB-3oEU5wtdV15b1EOYQIe5hCZ5DOD3piSo-ZbfYWH1mTJFE16T8V-uVuY9jDm0hClnGxrMB8giX_tZwhmSaQx2JiABMAE:gemini-hl=CkkACWuJV4Jq7gXnYGXm-CCWRGf1MNczIJ0yMsen8R98zb0fdd_v1HDcw_-Y0Gxw7WZu_GGVl89NUAGecp6EG6tM_DjudIlkdiK-EIrY7M8GGnMACWuJV31T-KTfj_kfyrGQHbGXZ7KunpXW6SzAgefOWjjwyayg6Iwu0SbTAuaaMQSQ8ufFGG6iBo8LYRPIidrB1YJS53ezUMIrhyU-FP7Nc8Boi7MnVyvN6x2wVXePw5OBeTd2MJhE9RaLVXVvihLIkRdpIAEwAQ",
        "id": 5
    },
    {
        "domain": ".google.com",
        "expirationDate": 1812127959.760433,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-1PAPISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "Y9HV5Kc8cM8vTBN6/AtmURmzxOh87hbr_v",
        "id": 6
    },
    {
        "domain": ".google.com",
        "expirationDate": 1812127959.758956,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "g.a0009QgRdowFVg6N3v6BpQPMjje79U-5QcNUBBs4ZRjnUujDzykElIlJU5gpR1Ai10pJezZ-OwACgYKAXISARESFQHGX2MiCVnL1NihqvD4LnuV0MvnjRoVAUF8yKrB8z8U8DweF9bo8g-g8wS20076",
        "id": 7
    },
    {
        "domain": ".google.com",
        "expirationDate": 1809751859.389926,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSIDCC",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AKEyXzVAyKvtTUw-QGilVJXOvGuqBvT4qbXMYO-OBcPaEle_kDmYlZSlGcaUC2ZNdRlK8XmzSGk",
        "id": 8
    },
    {
        "domain": ".google.com",
        "expirationDate": 1778216395.717927,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSIDRTS",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "sidts-CjYBhkeRd79-QayrHTq0xcAtJ1zrPafafI90wZ3Lwmgw-1XR1CHSE9Mf44cjeX0Oq41whlwRSx0QAA",
        "id": 9
    },
    {
        "domain": ".google.com",
        "expirationDate": 1809751795.717731,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSIDTS",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "sidts-CjYBhkeRd79-QayrHTq0xcAtJ1zrPafafI90wZ3Lwmgw-1XR1CHSE9Mf44cjeX0Oq41whlwRSx0QAA",
        "id": 10
    },
    {
        "domain": ".google.com",
        "expirationDate": 1812127959.760542,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-3PAPISID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "Y9HV5Kc8cM8vTBN6/AtmURmzxOh87hbr_v",
        "id": 11
    },
    {
        "domain": ".google.com",
        "expirationDate": 1812127959.759207,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "g.a0009QgRdowFVg6N3v6BpQPMjje79U-5QcNUBBs4ZRjnUujDzykEKhEpDvOfxNfv1gnzVhDgLgACgYKAWsSARESFQHGX2MiIwf6hYr88_aIGDSFLiAoQxoVAUF8yKqRZuK5eO2tinjqLjyjgesF0076",
        "id": 12
    },
    {
        "domain": ".google.com",
        "expirationDate": 1809751859.390035,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSIDCC",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AKEyXzXSUv1rfkFdsoQmvFPvVxfNfT1m0v8E2MPcTvaYyb6q42v81DaVQnG0eZiyryy7x-Ft5l1N",
        "id": 13
    },
    {
        "domain": ".google.com",
        "expirationDate": 1778216395.7181,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSIDRTS",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "sidts-CjYBhkeRd79-QayrHTq0xcAtJ1zrPafafI90wZ3Lwmgw-1XR1CHSE9Mf44cjeX0Oq41whlwRSx0QAA",
        "id": 14
    },
    {
        "domain": ".google.com",
        "expirationDate": 1809751795.718025,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSIDTS",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "sidts-CjYBhkeRd79-QayrHTq0xcAtJ1zrPafafI90wZ3Lwmgw-1XR1CHSE9Mf44cjeX0Oq41whlwRSx0QAA",
        "id": 15
    },
    {
        "domain": ".google.com",
        "expirationDate": 1783131940.378771,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-BUCKET",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "CPoD",
        "id": 16
    },
    {
        "domain": ".google.com",
        "expirationDate": 1779623964.925612,
        "hostOnly": false,
        "httpOnly": true,
        "name": "AEC",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AaJma5sjoHtK83BirO7ZAAAo_FS6Cj6xsPP0wTZC8lvUZSjrRaHfRvNqIF0",
        "id": 17
    },
    {
        "domain": ".google.com",
        "expirationDate": 1812127959.760211,
        "hostOnly": false,
        "httpOnly": false,
        "name": "APISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "RI-HjCC3Ay9zGYNG/AmG8_CYsDra4vDn6D",
        "id": 18
    },
    {
        "domain": ".google.com",
        "expirationDate": 1812127959.759938,
        "hostOnly": false,
        "httpOnly": true,
        "name": "HSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "AzNF-yxlSqbjf5wAD",
        "id": 19
    },
    {
        "domain": ".google.com",
        "expirationDate": 1793968839.862595,
        "hostOnly": false,
        "httpOnly": true,
        "name": "NID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "531=CJgvfPapZeiEyR5r7hVyUsqPW0FxYLUe15aKEGP0gnG1tmeHPeLp5DfkMkHatEcDZcP9DCyLjBrnODtQ5ms4Ivhby0axDvmcB1qheBqbi7rXUinkuXquX_pXMRsRDWoenop9dqXIiMpsIRT6sIl5-rYNnl_SBVTpVeS7rYzSMOG6oxNpL9-uexE5lEEl4gKf-w3CQf_6KYwqZNGez-vSz7J0mp724QYGWZDnGhB7OShmkxLupYiXqtiBLzXyGDNEcZQQMzWJULQmvOmnR0-30E1evjuE-KwFbNM5CeaP07VR12ry5RyOLo7QTRG_18Zb-oVNvh9oWDimf3AAaiL_EelAMAakKrI2NmEdJ9yisOAPZcj-mG1t7jOaS7cydNTCXuFLMzXWeTaqj0QGgKRqg7jq0L2_MYX6Zn830xVqN8YHilT1ON1AacSjMnY4rjH5sWCprPwlR-9wl66Ca_lnVgy-afUjC4rWYMjuduU_0N66xtue8i3TEJPS2oW64XJUdapgdwD--RiNICi49eePw2x0mVbu6EvxaAxvde9NAY0j6-V9ap0Y2ZYPpEru1HDRdxmEp--NbgoaeLsJRQWYSteLCegZ3NMJtKXIfdQO9s_KNlw3Hgko1UbDpmLyfThArPRDz_RxYNNQZeOEL25crxDaMiTuI362aAFTR6YuHRBFGoDZB1hq8g1RzWIdyUxfTKpX9xHPagYgO1G9eEfX1YLlWEv8NLjRJlJCvPEuofD8A1RdC72ZQuj1sjJU2yMlnLOA7twcv3OUc38_45vtnBisfhh-vjAW3ImM348hLN0spLvG37NPyKOwoabK3Hb_A358wM9L7zzWoH0lB11meFvNp7u8nuMIoKPoNDq2qy9gc_a0Ev_gif6x1m6BQmwNTvCsyuP2aptuwdKYA2qGaWCclbJm6VYcJgRNg4SyAXiaT1SLOIr_2Vj7o6df9SvukjNt4WT4ZJDTc-bjtgHRCzhzMH88dVv75tM4RZutRM1UXmuBNfvrZspv6nYvsqF1WuZzCaLtDHG7SSen0gGt2hemb6PP6dw-nMdwcJHeFw84QtaZOv8L3qqSa8GnCYQK8sUdNBsGUI79qznejKBUZwWha5p6lEO8tF0",
        "id": 20
    },
    {
        "domain": ".google.com",
        "expirationDate": 1812127959.760328,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SAPISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "Y9HV5Kc8cM8vTBN6/AtmURmzxOh87hbr_v",
        "id": 21
    },
    {
        "domain": ".google.com",
        "expirationDate": 1792574521.075714,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SEARCH_SAMESITE",
        "path": "/",
        "sameSite": "strict",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "CgQI16AB",
        "id": 22
    },
    {
        "domain": ".google.com",
        "expirationDate": 1812127959.758709,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "g.a0009QgRdowFVg6N3v6BpQPMjje79U-5QcNUBBs4ZRjnUujDzykETZBsrTE-HYdUo3ZIh7lI2AACgYKASsSARESFQHGX2MiY_mzE7jgdCX9PCDawjWQPxoVAUF8yKqyTjfBVJXBL5nglHyb4cVY0076",
        "id": 23
    },
    {
        "domain": ".google.com",
        "expirationDate": 1809751859.389818,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SIDCC",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "AKEyXzUi1t6CWzTFqGsuMD8GgjMlhEKoN9oOO88-BGU91Cxis3b9hRJtWP-P8a3TwNjBZbWMKLLB",
        "id": 24
    },
    {
        "domain": ".google.com",
        "expirationDate": 1812127959.760103,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AATuRE3UZ6mCtv0ys",
        "id": 25
    }
]