[
    {
        "domain": ".gemini.google.com",
        "expirationDate": 1812775883.174657,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GA1.1.884687835.1774622835",
        "id": 1
    },
    {
        "domain": ".gemini.google.com",
        "expirationDate": 1812775883.173899,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga_BF8Q35BMLM",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GS2.1.s1778215160$o11$g1$t1778215883$j60$l0$h0",
        "id": 2
    },
    {
        "domain": ".gemini.google.com",
        "expirationDate": 1812775883.064876,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga_WC57KJ50ZZ",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GS2.1.s1778215158$o12$g1$t1778215883$j59$l0$h0",
        "id": 3
    },
    {
        "domain": ".gemini.google.com",
        "expirationDate": 1782398834,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_gcl_au",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1.1.1985158479.1774622834",
        "id": 4
    },
    {
        "domain": ".gemini.google.com",
        "expirationDate": 1785991882,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_gcl_aw",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GCL.1778215882.Cj0KCQjw1ZjOBhCmARIsADDuFTAh6FQmafpxQWcEkzKvLNVN8rumbinqpYNoDJk6NEoMm1bxD1VIJ3kaAu-FEALw_wcB",
        "id": 5
    },
    {
        "domain": ".gemini.google.com",
        "expirationDate": 1785991882,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_gcl_dc",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GCL.1778215882.Cj0KCQjw1ZjOBhCmARIsADDuFTAh6FQmafpxQWcEkzKvLNVN8rumbinqpYNoDJk6NEoMm1bxD1VIJ3kaAu-FEALw_wcB",
        "id": 6
    },
    {
        "domain": ".gemini.google.com",
        "expirationDate": 1785991882,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_gcl_gs",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "2.1.k1$i1778215881$u235777175",
        "id": 7
    },
    {
        "domain": ".gemini.google.com",
        "expirationDate": 1779045520.372972,
        "hostOnly": false,
        "httpOnly": true,
        "name": "COMPASS",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "gemini-pd=CjwACWuJV93jFYb_b6k1ZbZc5AVi75OXfwVJx6huPFdJgLZgT-iphNSBtyIyTho-2Gurv4U86El7hPmdVFUQlu74zwYaZgAJa4lXi3X0DDL-AISvltu0QPdzXOiU5YPE6pwnPqAFQbVAQiyDQzfyJcjFPcM8KOMpH_JLqWlH8-m39km0XEXgTxMBnbZRLAtBT4z1kWrNe2VrQddQP1XnRSRHQ8oLzm8LwgjBwyABKnAIARCV7vjPBhpmAAlriVdrx-7hue3_-l9euNiE4DVYVITyYYAiq7EcjLmTLE-BbuqwS-jXddy1uyihNHqF-YHTVVY9Xu4PNBmw__OobwezFEJhdXd5AUwZNErYy0hweZJ3fp--GTJDRaV2VD_r4lOxMAE",
        "id": 8
    },
    {
        "domain": ".google.com",
        "expirationDate": 1811955551.214767,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-1PAPISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "lROMQXVhtTCX42O1/AOfPpdRu_6Mff8RBj",
        "id": 9
    },
    {
        "domain": ".google.com",
        "expirationDate": 1811955551.214135,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "g.a0009QhJhEemKBOsi1xC8Cpzxf_rB4hcFqwqECveQOlTebBbUgJILiPPLfVbIDPc9MVN2FskIwACgYKAV0SARESFQHGX2MiHlXF1N2uUE59UBCfPesiVhoVAUF8yKqmRM5qisxehZmQvv7HgqmQ0076",
        "id": 10
    },
    {
        "domain": ".google.com",
        "expirationDate": 1809751884.307848,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSIDCC",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AKEyXzUWN8Sw3Jn1MzBn00WqoMCsdTD3eW0HZp-j0WMJQmkWjA-xqVrsH8GIGVuB5hlimLW33YY",
        "id": 11
    },
    {
        "domain": ".google.com",
        "expirationDate": 1778216395.691206,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSIDRTS",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "sidts-CjYBhkeRd1TpZOzeHoduW6MCgzAotQKmTcJge-dZc74qNM1BpM7PlYoT5xkefT4jgGH8pcI5QFkQAA",
        "id": 12
    },
    {
        "domain": ".google.com",
        "expirationDate": 1809751795.691011,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSIDTS",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "sidts-CjYBhkeRd1TpZOzeHoduW6MCgzAotQKmTcJge-dZc74qNM1BpM7PlYoT5xkefT4jgGH8pcI5QFkQAA",
        "id": 13
    },
    {
        "domain": ".google.com",
        "expirationDate": 1811955551.214816,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-3PAPISID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "lROMQXVhtTCX42O1/AOfPpdRu_6Mff8RBj",
        "id": 14
    },
    {
        "domain": ".google.com",
        "expirationDate": 1811955551.214189,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "g.a0009QhJhEemKBOsi1xC8Cpzxf_rB4hcFqwqECveQOlTebBbUgJIUIeoWWMqq9E7TcyZkcdl3AACgYKAWkSARESFQHGX2MiA-dVUkVnxRmn8Xwx7WLXEBoVAUF8yKrGdzavfS2ryVoLDs4raa2A0076",
        "id": 15
    },
    {
        "domain": ".google.com",
        "expirationDate": 1809751884.307933,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSIDCC",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AKEyXzUg8HjxpM_oaEW4De8eD4QlHNTDyNmYx_1GCu9ZGB09rUPzW913uknrt-EYlSTLS-lYvA",
        "id": 16
    },
    {
        "domain": ".google.com",
        "expirationDate": 1778216395.691372,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSIDRTS",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "sidts-CjYBhkeRd1TpZOzeHoduW6MCgzAotQKmTcJge-dZc74qNM1BpM7PlYoT5xkefT4jgGH8pcI5QFkQAA",
        "id": 17
    },
    {
        "domain": ".google.com",
        "expirationDate": 1809751795.691291,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSIDTS",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "sidts-CjYBhkeRd1TpZOzeHoduW6MCgzAotQKmTcJge-dZc74qNM1BpM7PlYoT5xkefT4jgGH8pcI5QFkQAA",
        "id": 18
    },
    {
        "domain": ".google.com",
        "expirationDate": 1783305704.690647,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-BUCKET",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "COkB",
        "id": 19
    },
    {
        "domain": ".google.com",
        "expirationDate": 1779623919.56241,
        "hostOnly": false,
        "httpOnly": true,
        "name": "AEC",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AaJma5tNBIKQBSz-ssOM42e1tsz3lmhfgvKNLGMNmGzrmS9tAQ7hQqsBvqk",
        "id": 20
    },
    {
        "domain": ".google.com",
        "expirationDate": 1811955551.214664,
        "hostOnly": false,
        "httpOnly": false,
        "name": "APISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "MZdHBoP0KJ0YjoIf/AO7xDawt-qtLi4nBU",
        "id": 21
    },
    {
        "domain": ".google.com",
        "expirationDate": 1811955551.214439,
        "hostOnly": false,
        "httpOnly": true,
        "name": "HSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "AQZBd81ovhbgpIlYI",
        "id": 22
    },
    {
        "domain": ".google.com",
        "expirationDate": 1793964806.126259,
        "hostOnly": false,
        "httpOnly": true,
        "name": "NID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "531=kb3Kne4LURJJkc09sgYjFFcoTiazeartV1-FtVBZwxga0ZfjOPkVG-vRXEySvfologhy-jUJ79tVQ0f2Ba2BxASLQ8NtVrvn4sLJZsUA7id3Vaw-47Fl4FuGUZmuNbZnFDUSxlH8CkXhR5JMX9O213w9ORh6-67rbOZU-QiZ68mPbB06iCxzshrMCRnq1FKyxw7rbQcFabL3GtvPFUvyT-ASnwRUM8m_u8B-OISJH4KeZmtA2ElBMWX1u2ax2LwAwo0HpJs8EVZRUlWbjWvRbv1jph9uUGiYDygOckcboLb4bWqejuiSqd2Fm9exFx60pS7lgSiDvFBDjtxgq893qd_VVpdQkg-sy_vgDFHPWC5NsBgSmGSAFtfiRYT4iVA6xYlGp5zRUiwqy0rMnThb2b3e7SDM-uXuZfx5L1nTK99VG4x_4ZSQ35nxG6MNo6diovKYlMbsDcMbvz6rvKIaqE7NIbXo62QbrHqvLxmbLCbOjRpSSPkSpA-Qa5T6owT-D8v46mSFsqt8da8TcwOWJOysR4dJ1uhoztyR_wI9FgwK3oE9f9pd3jEYf8o3c3Gnw6P5Wv1lRTnxRvlnggMwJFuoGIRVCvuBkTXR7IUCcrtgL1S5-kFpxmfyL2JpUYEMcO_BySO8X4kwE-gPcz3XtfuEMDJI-zRnfO6aiUklUMFgPgA6LdylUHOxQJKR8axh2qP_W7CjYASFxr6QMBrirABMohllCiGboM4Ramo3TlTOOsbnMA4VJrp7XC77VOag168t5I9dwr7YjzcwS7-J9Hkzq8iDil7QR9kJKQjoLsNsOrdjVX51eVONP4l_P78B_Jza7p4gDfqsMjeDZ2rLnNi5G3nnXok-ghfVYijNBOdUTzDUQFk2X0Am3KPKFQ4ciKy_XONA8ZcOgWsxJpjwR7n93aOVIkWpbikoaXF6CwvlxezsmxUaVJ-RypYQCzuD4c-KEb9S-_C91uGBl-vmGIvMVj-cDpendibI4uqMqjllHEt5cZuaeW73yFNk7h-KenvgpnP47Nxwhyxe0zD7Gd4ZW-i1bBc",
        "id": 23
    },
    {
        "domain": ".google.com",
        "expirationDate": 1811955551.214716,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SAPISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "lROMQXVhtTCX42O1/AOfPpdRu_6Mff8RBj",
        "id": 24
    },
    {
        "domain": ".google.com",
        "expirationDate": 1792946457.910834,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SEARCH_SAMESITE",
        "path": "/",
        "sameSite": "strict",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "CgQI26AB",
        "id": 25
    },
    {
        "domain": ".google.com",
        "expirationDate": 1811955551.214002,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "g.a0009QhJhEemKBOsi1xC8Cpzxf_rB4hcFqwqECveQOlTebBbUgJIK3AsRPKiXc8dTJS9ROH-mgACgYKAbMSARESFQHGX2MiZxHvpyVWDwQjGYzksU9WJxoVAUF8yKoxELrF1mmZXtjau4YFzQVC0076",
        "id": 26
    },
    {
        "domain": ".google.com",
        "expirationDate": 1809751884.307767,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SIDCC",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "AKEyXzXfj4ovWB7h6mxqLrEosSF2yRDXjgr7vrEVs7qu9wfiabrSQjOcnB9Eoe0cmvK2jkCuDQ",
        "id": 27
    },
    {
        "domain": ".google.com",
        "expirationDate": 1811955551.214529,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "Aj9ENT3nyU7-Yewnl",
        "id": 28
    }
]