[
    {
        "domain": ".gemini.google.com",
        "expirationDate": 1812779620.47112,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GA1.1.884687835.1774622835",
        "id": 1
    },
    {
        "domain": ".gemini.google.com",
        "expirationDate": 1812779620.470007,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga_BF8Q35BMLM",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GS2.1.s1778219620$o12$g0$t1778219620$j60$l0$h0",
        "id": 2
    },
    {
        "domain": ".gemini.google.com",
        "expirationDate": 1812779619.775517,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga_WC57KJ50ZZ",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GS2.1.s1778219618$o13$g1$t1778219619$j59$l0$h0",
        "id": 3
    },
    {
        "domain": ".gemini.google.com",
        "expirationDate": 1782398834,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_gcl_au",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1.1.1985158479.1774622834",
        "id": 4
    },
    {
        "domain": ".gemini.google.com",
        "expirationDate": 1785995619,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_gcl_aw",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GCL.1778219619.Cj0KCQjw1ZjOBhCmARIsADDuFTAh6FQmafpxQWcEkzKvLNVN8rumbinqpYNoDJk6NEoMm1bxD1VIJ3kaAu-FEALw_wcB",
        "id": 5
    },
    {
        "domain": ".gemini.google.com",
        "expirationDate": 1785995619,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_gcl_dc",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GCL.1778219619.Cj0KCQjw1ZjOBhCmARIsADDuFTAh6FQmafpxQWcEkzKvLNVN8rumbinqpYNoDJk6NEoMm1bxD1VIJ3kaAu-FEALw_wcB",
        "id": 6
    },
    {
        "domain": ".gemini.google.com",
        "expirationDate": 1785995618,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_gcl_gs",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "2.1.k1$i1778219618$u235777175",
        "id": 7
    },
    {
        "domain": ".gemini.google.com",
        "expirationDate": 1779045520.372972,
        "hostOnly": false,
        "httpOnly": true,
        "name": "COMPASS",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "gemini-pd=CjwACWuJV93jFYb_b6k1ZbZc5AVi75OXfwVJx6huPFdJgLZgT-iphNSBtyIyTho-2Gurv4U86El7hPmdVFUQlu74zwYaZgAJa4lXi3X0DDL-AISvltu0QPdzXOiU5YPE6pwnPqAFQbVAQiyDQzfyJcjFPcM8KOMpH_JLqWlH8-m39km0XEXgTxMBnbZRLAtBT4z1kWrNe2VrQddQP1XnRSRHQ8oLzm8LwgjBwyABKnAIARCV7vjPBhpmAAlriVdrx-7hue3_-l9euNiE4DVYVITyYYAiq7EcjLmTLE-BbuqwS-jXddy1uyihNHqF-YHTVVY9Xu4PNBmw__OobwezFEJhdXd5AUwZNErYy0hweZJ3fp--GTJDRaV2VD_r4lOxMAE",
        "id": 8
    },
    {
        "domain": ".google.com",
        "expirationDate": 1811955551.214767,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-1PAPISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "lROMQXVhtTCX42O1/AOfPpdRu_6Mff8RBj",
        "id": 9
    },
    {
        "domain": ".google.com",
        "expirationDate": 1811955551.214135,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "g.a0009QhJhEemKBOsi1xC8Cpzxf_rB4hcFqwqECveQOlTebBbUgJILiPPLfVbIDPc9MVN2FskIwACgYKAV0SARESFQHGX2MiHlXF1N2uUE59UBCfPesiVhoVAUF8yKqmRM5qisxehZmQvv7HgqmQ0076",
        "id": 10
    },
    {
        "domain": ".google.com",
        "expirationDate": 1809755622.614886,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSIDCC",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AKEyXzXZW7L9pFgN3LLjAPRY63RsKfGOuhRvvHTD_goTWLYy4pItoYP5MyF_rc_0nidCKGqK6rY",
        "id": 11
    },
    {
        "domain": ".google.com",
        "expirationDate": 1778220118.865947,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSIDRTS",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "sidts-CjYBhkeRd0NfoNvSAowUhvEuz0DYBGQbdFY1mKXr5idVULo1AckM7N4hbh2ypOZlsISJuLa5biwQAA",
        "id": 12
    },
    {
        "domain": ".google.com",
        "expirationDate": 1809755518.865737,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSIDTS",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "sidts-CjYBhkeRd0NfoNvSAowUhvEuz0DYBGQbdFY1mKXr5idVULo1AckM7N4hbh2ypOZlsISJuLa5biwQAA",
        "id": 13
    },
    {
        "domain": ".google.com",
        "expirationDate": 1811955551.214816,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-3PAPISID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "lROMQXVhtTCX42O1/AOfPpdRu_6Mff8RBj",
        "id": 14
    },
    {
        "domain": ".google.com",
        "expirationDate": 1811955551.214189,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "g.a0009QhJhEemKBOsi1xC8Cpzxf_rB4hcFqwqECveQOlTebBbUgJIUIeoWWMqq9E7TcyZkcdl3AACgYKAWkSARESFQHGX2MiA-dVUkVnxRmn8Xwx7WLXEBoVAUF8yKrGdzavfS2ryVoLDs4raa2A0076",
        "id": 15
    },
    {
        "domain": ".google.com",
        "expirationDate": 1809755622.615158,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSIDCC",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AKEyXzX_XLpplP_GBse3pboPZ6N6m1UmqxIhbq8Ioe8OgNLAB-wvgQlQx9AE60luKLrJ85BKYQ",
        "id": 16
    },
    {
        "domain": ".google.com",
        "expirationDate": 1778220118.866112,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSIDRTS",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "sidts-CjYBhkeRd0NfoNvSAowUhvEuz0DYBGQbdFY1mKXr5idVULo1AckM7N4hbh2ypOZlsISJuLa5biwQAA",
        "id": 17
    },
    {
        "domain": ".google.com",
        "expirationDate": 1809755518.866035,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSIDTS",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "sidts-CjYBhkeRd0NfoNvSAowUhvEuz0DYBGQbdFY1mKXr5idVULo1AckM7N4hbh2ypOZlsISJuLa5biwQAA",
        "id": 18
    },
    {
        "domain": ".google.com",
        "expirationDate": 1783305704.690647,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-BUCKET",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "COkB",
        "id": 19
    },
    {
        "domain": ".google.com",
        "expirationDate": 1779623919.56241,
        "hostOnly": false,
        "httpOnly": true,
        "name": "AEC",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AaJma5tNBIKQBSz-ssOM42e1tsz3lmhfgvKNLGMNmGzrmS9tAQ7hQqsBvqk",
        "id": 20
    },
    {
        "domain": ".google.com",
        "expirationDate": 1811955551.214664,
        "hostOnly": false,
        "httpOnly": false,
        "name": "APISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "MZdHBoP0KJ0YjoIf/AO7xDawt-qtLi4nBU",
        "id": 21
    },
    {
        "domain": ".google.com",
        "expirationDate": 1811955551.214439,
        "hostOnly": false,
        "httpOnly": true,
        "name": "HSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "AQZBd81ovhbgpIlYI",
        "id": 22
    },
    {
        "domain": ".google.com",
        "expirationDate": 1793964805.557251,
        "hostOnly": false,
        "httpOnly": true,
        "name": "NID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "531=EPd37yCpKZnUDVp80Frqm-6cLSHJbojjWE8OweiAEAc60Ubh5teCkB2W1wbmQan5p_WV8rV85DAttoOgWqIop495gihkQ8DWH24yBVFTM8K0vlMPzvRZfJDLr8kmbDJd9lFy8JyQBfOHicvPHPTpgOnD7xCJNmvI0MEAcDhslNhKIm0v9AsZVWwPbatdqhRgPMEWCyAlwVtBa-tpBIdtw_-k8Gkw0IxuqLcoXFpWEiIi8wBQ9uHc3jnBlnmO-ldHFZsR_6Z4EsP7xFsK41v_TJxtf3X7NvTUcRIpBiKK_-fvNhqoQYBRF2jz_1OUOE1R6YKzFujq_Qr2H8uFiTRJGalumkdf47XkHlVrtOrWBGaj78rfk5WsI57aabhUALbe66EzoWpTNhwI7qhPtZKT_n4CdC9JbBmxDV5trC8hAIu3V2xzaxoP0SPUpzPbb6D-Ur7gT2NpWZq7-o4pLwPW8pPgQEM57rkaubU2p2CVr6U4Qo4Bl5UrAAWdReV6AuAYNnkHyuvjYa2ZP3mp13gSII_xIoO9kmGJoo-JDbjVjLZUSMgYA9WzvCPQRh4baS1O5KKCvjQj7Y1dSRfjkn6bRnDJoCUBpQPS5sExoX73D5pdvaxKfb1QX5IswB3X_hmbbqQmt6ZPfykhO--gb8RcrOq0xQ1ocxdZKq40eq8eBM2UjGqIlRgcy7vdKkWgFBHahc1IaTeKKKiVoPlVQ695o99-cDAtU5NhlTq5mXRIrvlyoGjnOI22QD2wF1oJPKO4QW1f44BZ_R7cIYQYmHIZM0hAtPc7UmxtydyuIWscYhC8XqDy2JPmpMar05b9OeN9CgvvHY_VyFRVS6984CzKvGpF4flWbJp9EL67jW4d6IHtzR9lVsA_aMcoTC-W5fJU23CBBRXB1ui3UR1-4uDzuGl9kKgWMkCbgKjknzDUcyJItOydYCauDZMNunfP-FRa836JA9AHBl8V_txKB12P5u4huu3KcW7Xynp7u-wGoKjX0h-i_o07ONAsw0SJJ4LF_aDNut0Aq-zg6qZsG2ZHBPj-JG-IpLM",
        "id": 23
    },
    {
        "domain": ".google.com",
        "expirationDate": 1811955551.214716,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SAPISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "lROMQXVhtTCX42O1/AOfPpdRu_6Mff8RBj",
        "id": 24
    },
    {
        "domain": ".google.com",
        "expirationDate": 1792946457.910834,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SEARCH_SAMESITE",
        "path": "/",
        "sameSite": "strict",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "CgQI26AB",
        "id": 25
    },
    {
        "domain": ".google.com",
        "expirationDate": 1811955551.214002,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "g.a0009QhJhEemKBOsi1xC8Cpzxf_rB4hcFqwqECveQOlTebBbUgJIK3AsRPKiXc8dTJS9ROH-mgACgYKAbMSARESFQHGX2MiZxHvpyVWDwQjGYzksU9WJxoVAUF8yKoxELrF1mmZXtjau4YFzQVC0076",
        "id": 26
    },
    {
        "domain": ".google.com",
        "expirationDate": 1809755622.614722,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SIDCC",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "AKEyXzUnNgdDY95HBKmBYg7b7SofPkppRRoq082AMcTj_-3uQNKGGB82H6ay3kMSFR0XUvZcMg",
        "id": 27
    },
    {
        "domain": ".google.com",
        "expirationDate": 1811955551.214529,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "Aj9ENT3nyU7-Yewnl",
        "id": 28
    }
]