[
    {
        "domain": ".gemini.google.com",
        "expirationDate": 1812299475.345048,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GA1.1.2092490730.1770214179",
        "id": 1
    },
    {
        "domain": ".gemini.google.com",
        "expirationDate": 1812299475.341639,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga_BF8Q35BMLM",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GS2.1.s1777739475$o123$g0$t1777739475$j60$l0$h0",
        "id": 2
    },
    {
        "domain": ".gemini.google.com",
        "expirationDate": 1812299474.987446,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga_WC57KJ50ZZ",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GS2.1.s1777737672$o153$g1$t1777739474$j59$l0$h0",
        "id": 3
    },
    {
        "domain": ".gemini.google.com",
        "expirationDate": 1782639016,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_gcl_au",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1.1.792299493.1774863016",
        "id": 4
    },
    {
        "domain": ".gemini.google.com",
        "expirationDate": 1778562480.025739,
        "hostOnly": false,
        "httpOnly": true,
        "name": "COMPASS",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "gemini-pd=CjwACWuJV93jFYb_b6k1ZbZc5AVi75OXfwVJx6huPFdJgLZgT-iphNSBtyIyTho-2Gurv4U86El7hPmdVFUQ35nazwYaZgAJa4lXpMUDqFVhvXayopoShCupMZ4RLawHcFAuWARBhjOrJVB-3oEU5wtdV15b1EOYQIe5hCZ5DOD3piSo-ZbfYWH1mTJFE16T8V-uVuY9jDm0hClnGxrMB8giX_tZwhmSaQx2JiABMAE:gemini-hl=CkkACWuJV4Jq7gXnYGXm-CCWRGf1MNczIJ0yMsen8R98zb0fdd_v1HDcw_-Y0Gxw7WZu_GGVl89NUAGecp6EG6tM_DjudIlkdiK-ELCw288GGnMACWuJV31T-KTfj_kfyrGQHbGXZ7KunpXW6SzAgefOWjjwyayg6Iwu0SbTAuaaMQSQ8ufFGG6iBo8LYRPIidrB1YJS53ezUMIrhyU-FP7Nc8Boi7MnVyvN6x2wVXePw5OBeTd2MJhE9RaLVXVvihLIkRdpIAEwAQ",
        "id": 5
    },
    {
        "domain": ".google.com",
        "expirationDate": 1812127959.760433,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-1PAPISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "Y9HV5Kc8cM8vTBN6/AtmURmzxOh87hbr_v",
        "id": 6
    },
    {
        "domain": ".google.com",
        "expirationDate": 1812127959.758956,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "g.a0009QgRdowFVg6N3v6BpQPMjje79U-5QcNUBBs4ZRjnUujDzykElIlJU5gpR1Ai10pJezZ-OwACgYKAXISARESFQHGX2MiCVnL1NihqvD4LnuV0MvnjRoVAUF8yKrB8z8U8DweF9bo8g-g8wS20076",
        "id": 7
    },
    {
        "domain": ".google.com",
        "expirationDate": 1809275482.680351,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSIDCC",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AKEyXzVCEEFsvi5IPDubpJbQoO93k6ww_aK4jHk7NXh5LeXGns8hBzh56qGi5_Q5QeJ0LQ1X4UQ",
        "id": 8
    },
    {
        "domain": ".google.com",
        "expirationDate": 1777740055.020103,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSIDRTS",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "sidts-CjYBhkeRd4eUcYD0enqiPZX9zdhlUzjLHgB_bgJSHyvwMI116JphBWjHI8NClMWu2EIzkvDjaYgQAA",
        "id": 9
    },
    {
        "domain": ".google.com",
        "expirationDate": 1809275455.019725,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSIDTS",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "sidts-CjYBhkeRd4eUcYD0enqiPZX9zdhlUzjLHgB_bgJSHyvwMI116JphBWjHI8NClMWu2EIzkvDjaYgQAA",
        "id": 10
    },
    {
        "domain": ".google.com",
        "expirationDate": 1812127959.760542,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-3PAPISID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "Y9HV5Kc8cM8vTBN6/AtmURmzxOh87hbr_v",
        "id": 11
    },
    {
        "domain": ".google.com",
        "expirationDate": 1812127959.759207,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "g.a0009QgRdowFVg6N3v6BpQPMjje79U-5QcNUBBs4ZRjnUujDzykEKhEpDvOfxNfv1gnzVhDgLgACgYKAWsSARESFQHGX2MiIwf6hYr88_aIGDSFLiAoQxoVAUF8yKqRZuK5eO2tinjqLjyjgesF0076",
        "id": 12
    },
    {
        "domain": ".google.com",
        "expirationDate": 1809275482.680625,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSIDCC",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AKEyXzXPAIklVRCVG-fCUPFe1usoejV6nWVqsBk5n42pfi0N5-ypM5KMl7LXd52tExubH__6ZyP0",
        "id": 13
    },
    {
        "domain": ".google.com",
        "expirationDate": 1777740055.020578,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSIDRTS",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "sidts-CjYBhkeRd4eUcYD0enqiPZX9zdhlUzjLHgB_bgJSHyvwMI116JphBWjHI8NClMWu2EIzkvDjaYgQAA",
        "id": 14
    },
    {
        "domain": ".google.com",
        "expirationDate": 1809275455.020344,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSIDTS",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "sidts-CjYBhkeRd4eUcYD0enqiPZX9zdhlUzjLHgB_bgJSHyvwMI116JphBWjHI8NClMWu2EIzkvDjaYgQAA",
        "id": 15
    },
    {
        "domain": ".google.com",
        "expirationDate": 1783131940.378771,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-BUCKET",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "CPoD",
        "id": 16
    },
    {
        "domain": ".google.com",
        "expirationDate": 1779623969.604724,
        "hostOnly": false,
        "httpOnly": true,
        "name": "AEC",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AaJma5vukV7lSqB-Hk8TuSxFUacufiubY4-i5Id0kj3y60L-4N7yOJPtH1k",
        "id": 17
    },
    {
        "domain": ".google.com",
        "expirationDate": 1812127959.760211,
        "hostOnly": false,
        "httpOnly": false,
        "name": "APISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "RI-HjCC3Ay9zGYNG/AmG8_CYsDra4vDn6D",
        "id": 18
    },
    {
        "domain": ".google.com",
        "expirationDate": 1812127959.759938,
        "hostOnly": false,
        "httpOnly": true,
        "name": "HSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "AzNF-yxlSqbjf5wAD",
        "id": 19
    },
    {
        "domain": ".google.com",
        "expirationDate": 1793468439.054218,
        "hostOnly": false,
        "httpOnly": true,
        "name": "NID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "531=BbPu6c2RvhhQlgVJmUsM3XYvg7hbb2HuoJvZn3A2CChoaNhY4DKUO9fdG51ydHZSHsfmb53rNpNOp26qTdgG31ypNRka_b9pxZej6E6S2BZI1kkWwZCH2yA1qB0EYi5msJgfOg7ZZMCwzu5IljK68jo1F5C5YrRWovIovA3Dbl7V5oMhMrHHU1LsFOA5befT0x-I59LFGxamblj7GwonMxO0usBKArIGD9LiB1yJOKOmH5ZV2s-8X4qx_B-PJn_8eFjR_elnOx87blF8yp-if2fq0SfU9rlfx0NoeB9VU7JMlC8pNV01MfbXautPgmsEmE27jvsFwckf9eqtR7qYRfMy-vEJ5uctrH3eY66OB1Ebh1rPcdQqv2GJgmx5r27qyjprJiy3hdGY-8mhTRfZwKcD3jZO0sW7ZXkbmy5xhKIdv0YX15UCop6ttiw5dj4RnudLA5KuE7_eBYNg8Qn4NGCGESPQXBXhuQMT3AT4V13rh7_3WNAVfvYSQu2ZlUZQD6kAmeAVfmOCRpmp8S3SuBXD6HmqgaxKzYcGEgh1iWyc4rZve1cneW9IIaQ3a2XSE6sTIvAsfaEfk5fZ_63ocbeXUEEz8BS21Rr196bIhzG5OpaOHVRswcQxwxjQg72ZgaQVLiTYwjuIcmE2v0AjAvb8iQFlCYukHK4sJv--M4u6TqXJ5_aQvH1O8ot1LMkFjeKBLStEzrf12MzXxdCIdb0EU_6ZbP-s-nLuOayGUk9hikahr_3VJxVfCtGWJF2ibPKdiEsqqiwy-rlsm2FDEleM2fkAndWxwA46yeyI91t46Kpw3zNsyqi61WZpgqK4w8nidBT28Ixpn6jHpLrWk71HtbyERS3TU3s_LHi4U_M9A_c5ixZKAiiEcn-Z7divuvwlI86YwuGbxZcx2y-MLprt9Pfh-AGlj7bYCbpNxEewHYq63zj_VQEg0inuDRHlKZaJIdevTMdF7q9W2O3Wibm0FfThZs1tW-9cUgKpD8oczIANNDBfsealt71Be0ruXavGZI48g0QeQehXSw_g64b28S85a2QAnbRP1dQWeaXTqHBwAGKHhzUf2uk8FzF_bYtNr4vFWhEJVw-lO32xrNLdz7xEdCk",
        "id": 20
    },
    {
        "domain": ".google.com",
        "expirationDate": 1812127959.760328,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SAPISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "Y9HV5Kc8cM8vTBN6/AtmURmzxOh87hbr_v",
        "id": 21
    },
    {
        "domain": ".google.com",
        "expirationDate": 1792574521.075714,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SEARCH_SAMESITE",
        "path": "/",
        "sameSite": "strict",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "CgQI16AB",
        "id": 22
    },
    {
        "domain": ".google.com",
        "expirationDate": 1812127959.758709,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "g.a0009QgRdowFVg6N3v6BpQPMjje79U-5QcNUBBs4ZRjnUujDzykETZBsrTE-HYdUo3ZIh7lI2AACgYKASsSARESFQHGX2MiY_mzE7jgdCX9PCDawjWQPxoVAUF8yKqyTjfBVJXBL5nglHyb4cVY0076",
        "id": 23
    },
    {
        "domain": ".google.com",
        "expirationDate": 1809275482.680087,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SIDCC",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "AKEyXzUqK4zqRqQGSixvlgyXhGyJtWLoJbItjMpc2ijmSpO6Q_K_73oYuXZiQ7K6al7Brc1Ql120",
        "id": 24
    },
    {
        "domain": ".google.com",
        "expirationDate": 1812127959.760103,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AATuRE3UZ6mCtv0ys",
        "id": 25
    }
]